language: csharp
solution: RateLimiting.sln
before_install:
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono .nuget/nuget.exe # Output NuGet's version number
install:
  - sudo apt-get install -y gtk-sharp2
  - mono .nuget/nuget.exe install Microsoft.NETCore -Version 5.0.0
  #- mono .nuget/nuget.exe Microsoft.NETCore.Portable.Compatibility -Version 1.0.0
  #- mono .nuget/nuget.exe restore RateLimiting.sln
mono:
  - latest

